name: Test
on:
  workflow_dispatch:
jobs:
  AutoSyncProcess:
    runs-on: ubuntu-latest
    steps:
    - name: Start
      run: |
          wget -qO- --no-check-certificate https://raw.githubusercontent.com/wn789/ernisnsuperspeed/master/superspeed.sh
          echo -e "3\n" | sudo bash 
