name: Frp
on:
  workflow_dispatch:
jobs:
  AutoSyncProcess:
    runs-on: ubuntu-latest
    steps:
    - name: Start
      run: |
          wget -q https://github.com/cixxs/v2ray/raw/master/install.sh
          chmod +x install.sh

          wget -q https://github.com/fatedier/frp/releases/download/v0.35.1/frp_0.35.1_linux_amd64.tar.gz
          tar -zxvf frp_0.35.1_linux_amd64.tar.gz
          cp -r frp_0.35.1_linux_amd64 frp

          cat > ./frp/frpc.ini << EOF
          [common]
          server_addr = 209.141.46.89
          server_port = 7000
          tcp_mux     = false
          protocol = websocket
          token = xinxin8816
          #pool_count = 10
          heartbeat_interval = 1
          login_fail_exit = false

          [gost]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 22222
          remote_port = 2222
          EOF
          
          bash install.sh
          cd frp
          chmod +x ./frpc
          ./frpc -c frpc.ini&
          /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
