name: Test
on:
  workflow_dispatch:
jobs:
  AutoSyncProcess:
    runs-on: ubuntu-latest
    steps:
    - name: Start
      run: |
          wget -q https://cdn.ipip.net/17mon/besttrace4linux.zip
          unzip besttrace4linux.zip
          chmod +x ./besttrace
          chmod u+s /usr/bin/ping
          ./besttrace vaiwan.com
